/**
 * 教案產生器 — 基於 18 頁投影片結構模板
 * 原始系統：Python PPTX 生成器（顏色感測器、雷射測距教案）
 * 結構：封面→目錄→規矩→目標→理論x4→過渡→實作→計時→程式→創意→整理→分享→再見→教師備→延伸
 */

export interface LessonSlide {
  slideNumber: number;
  title: string;
  type: "cover" | "toc" | "rules" | "objective" | "theory" | "transition" | "hands-on" | "timer" | "code" | "creative" | "cleanup" | "sharing" | "goodbye" | "teacher-note" | "extension";
  content: string[];
  icon: string;
}

export interface LessonPlan {
  topic: string;
  subtitle: string;
  totalSlides: number;
  estimatedTime: string;
  slides: LessonSlide[];
}

export function generateLessonPlan(topic: string): LessonPlan {
  const slides: LessonSlide[] = [
    {
      slideNumber: 1,
      title: topic,
      type: "cover",
      content: [
        `Matrix Mini R4 教案系列`,
        `人工智慧與機器人發展協會 AIRDA`,
        `適用對象：國小高年級 ~ 國中`,
      ],
      icon: "🎯",
    },
    {
      slideNumber: 2,
      title: "目錄",
      type: "toc",
      content: [
        "1. 學習目標",
        `2. ${topic}是什麼？`,
        `3. ${topic}的原理`,
        `4. ${topic}的應用`,
        "5. 生活中的實際案例",
        "6. 材料準備與接線",
        "7. 動手時間",
        "8. 程式範例",
        "9. 創意改造",
        "10. 課堂作業與分享",
      ],
      icon: "📋",
    },
    {
      slideNumber: 3,
      title: "上課規矩",
      type: "rules",
      content: [
        "1. 注意安全 — 不奔跑、不丟擲零件",
        "2. 尊重器材 — 輕拿輕放、用完歸位",
        "3. 專心聽講 — 老師說明時停下手邊動作",
        "4. 團隊合作 — 分工合作、互相幫忙",
        "5. 勇敢發問 — 有問題就舉手！",
      ],
      icon: "📏",
    },
    {
      slideNumber: 4,
      title: "學習目標",
      type: "objective",
      content: [
        `【知識學習】`,
        `• 了解${topic}的基本原理與科學背景`,
        `• 認識${topic}在生活中的應用場景`,
        `• 理解感測器如何將物理訊號轉換為數位資料`,
        ``,
        `【動手實作】`,
        `• 學會${topic}感測器的接線方式`,
        `• 能撰寫基礎 Arduino 程式讀取感測器數值`,
        `• 透過 Serial Monitor 觀察與分析數據`,
      ],
      icon: "🎓",
    },
    {
      slideNumber: 5,
      title: `${topic}是什麼？`,
      type: "theory",
      content: [
        `【定義】`,
        `${topic}的基本定義與概念說明`,
        ``,
        `【科學原理】`,
        `${topic}背後的科學原理與物理現象`,
        ``,
        `【歷史發展】`,
        `從早期發現到現代技術的演進過程`,
        ``,
        `💡 用簡單的比喻讓學生理解抽象概念`,
      ],
      icon: "🔬",
    },
    {
      slideNumber: 6,
      title: `${topic}的原理`,
      type: "theory",
      content: [
        `【感測原理】`,
        `感測器如何偵測與量測${topic}相關的物理量`,
        ``,
        `【訊號轉換】`,
        `從類比訊號到數位資料的轉換過程`,
        ``,
        `【關鍵參數】`,
        `• 量測範圍`,
        `• 精確度`,
        `• 響應時間`,
        `• 通訊介面（I2C / UART / Analog）`,
      ],
      icon: "⚙️",
    },
    {
      slideNumber: 7,
      title: `${topic}的應用`,
      type: "theory",
      content: [
        `【工業應用】`,
        `自動化產線中的${topic}技術應用`,
        ``,
        `【日常生活】`,
        `你身邊可能沒注意到的${topic}應用`,
        ``,
        `【機器人競賽】`,
        `在機器人比賽中如何運用${topic}取得優勢`,
        ``,
        `🤔 想想看：你在生活中還見過哪些${topic}的應用？`,
      ],
      icon: "🌍",
    },
    {
      slideNumber: 8,
      title: "生活中的實際案例",
      type: "theory",
      content: [
        `【案例 1】`,
        `具體的生活應用案例與圖片說明`,
        ``,
        `【案例 2】`,
        `另一個有趣的實際應用場景`,
        ``,
        `【案例 3】`,
        `最新的科技應用趨勢`,
        ``,
        `📸 配合實物照片或影片讓學生更有感覺`,
      ],
      icon: "💡",
    },
    {
      slideNumber: 9,
      title: `開始製作${topic}裝置！`,
      type: "transition",
      content: [
        `準備好了嗎？`,
        `接下來我們要動手做一個${topic}裝置！`,
        ``,
        `🔧 請確認桌上有以下材料：`,
        `• Matrix Mini R4 主控板 x1`,
        `• ${topic}感測器模組 x1`,
        `• 連接線 x1`,
        `• USB 傳輸線 x1`,
        `• 筆電（已安裝 Arduino IDE）`,
      ],
      icon: "🚀",
    },
    {
      slideNumber: 10,
      title: "動手時間 — 接線步驟",
      type: "hands-on",
      content: [
        `【Step 1】確認主控板已關機`,
        `【Step 2】找到感測器對應的連接埠（I2C / Analog / Digital）`,
        `【Step 3】將感測器排線插入對應埠位`,
        `【Step 4】檢查排線方向是否正確（注意防呆缺口）`,
        `【Step 5】接上 USB 傳輸線，連接筆電`,
        `【Step 6】開啟 Arduino IDE，選擇正確的板子與 COM Port`,
        ``,
        `⚠️ 注意：插拔排線時請先關閉電源！`,
      ],
      icon: "🔌",
    },
    {
      slideNumber: 11,
      title: "時間到！",
      type: "timer",
      content: [
        `⏰ 動手實作時間結束`,
        ``,
        `請確認：`,
        `✅ 接線完成`,
        `✅ 程式已上傳`,
        `✅ Serial Monitor 有數據輸出`,
        ``,
        `如果還沒完成，舉手請老師協助！`,
      ],
      icon: "⏰",
    },
    {
      slideNumber: 12,
      title: "程式範例",
      type: "code",
      content: [
        `#include <MatrixMiniR4.h>`,
        ``,
        `void setup() {`,
        `  Serial.begin(115200);`,
        `  MiniR4.begin();`,
        `  // 初始化${topic}感測器`,
        `  // MiniR4.I2C1.SensorName.begin();`,
        `  Serial.println("${topic} Sensor Ready!");`,
        `}`,
        ``,
        `void loop() {`,
        `  // 讀取感測器數值`,
        `  // int value = MiniR4.I2C1.SensorName.getValue();`,
        `  // Serial.print("Value: ");`,
        `  // Serial.println(value);`,
        `  delay(500);`,
        `}`,
      ],
      icon: "💻",
    },
    {
      slideNumber: 13,
      title: "創意改造",
      type: "creative",
      content: [
        `基礎版程式成功後，來挑戰進階任務！`,
        ``,
        `【挑戰 1】⭐`,
        `修改程式，加入 LED 指示燈回饋`,
        ``,
        `【挑戰 2】⭐⭐`,
        `結合馬達，根據感測器數值控制動作`,
        ``,
        `【挑戰 3】⭐⭐⭐`,
        `設計一個完整的自動化應用情境`,
        ``,
        `🏆 完成越多挑戰，獎勵越豐富！`,
      ],
      icon: "🎨",
    },
    {
      slideNumber: 14,
      title: "Clean Up 整理時間",
      type: "cleanup",
      content: [
        `1. 拔掉 USB 傳輸線`,
        `2. 小心拆下感測器排線`,
        `3. 感測器放回零件盒`,
        `4. 主控板放回指定位置`,
        `5. 桌面清潔整齊`,
        `6. 椅子推進桌下`,
        ``,
        `🧹 保持環境整潔是工程師的基本素養！`,
      ],
      icon: "🧹",
    },
    {
      slideNumber: 15,
      title: "分享時間",
      type: "sharing",
      content: [
        `你今天學到了什麼？`,
        ``,
        `💬 請分享：`,
        `• 你覺得最有趣的部分是什麼？`,
        `• 遇到了什麼困難？怎麼解決的？`,
        `• 你的創意改造做了什麼？`,
        `• 你想用${topic}做什麼專題？`,
        ``,
        `👏 每位同學都有機會上台分享 2 分鐘`,
      ],
      icon: "🗣️",
    },
    {
      slideNumber: 16,
      title: "下次見！",
      type: "goodbye",
      content: [
        `今天辛苦了！🎉`,
        ``,
        `下一堂課預告：`,
        `我們將學習更多感測器的應用`,
        `並開始組裝更複雜的機器人專題`,
        ``,
        `📝 回家作業：`,
        `觀察生活中 3 個使用${topic}的裝置`,
        `下次上課跟大家分享！`,
      ],
      icon: "👋",
    },
    {
      slideNumber: 17,
      title: "教師備註",
      type: "teacher-note",
      content: [
        `【授課建議】`,
        `• 理論部分控制在 15 分鐘內，搭配實物演示`,
        `• 實作時間建議 25-30 分鐘`,
        `• 準備 2-3 個已完成的範例供卡關學生參考`,
        ``,
        `【常見問題】`,
        `• 感測器沒反應 → 檢查排線方向與連接埠`,
        `• 數值異常 → 確認 begin() 是否正確呼叫`,
        `• 編譯失敗 → 檢查函式庫版本是否最新`,
        ``,
        `【差異化教學】`,
        `• 進度快的學生 → 引導挑戰進階任務`,
        `• 進度慢的學生 → 先確保基礎版成功運行`,
      ],
      icon: "📝",
    },
    {
      slideNumber: 18,
      title: "延伸探討",
      type: "extension",
      content: [
        `【深入思考】`,
        `• ${topic}感測器的量測極限在哪裡？`,
        `• 如何提高量測的精確度？`,
        `• 多個感測器組合能做出什麼效果？`,
        ``,
        `【進階主題】`,
        `• 數據濾波與訊號處理`,
        `• 感測器校正與標定`,
        `• AI 輔助的感測器數據分析`,
        ``,
        `【推薦資源】`,
        `• Matrix 官方文件與範例庫`,
        `• Arduino 感測器教學社群`,
        `• AIRDA 進階培訓課程`,
      ],
      icon: "🔍",
    },
  ];

  return {
    topic,
    subtitle: `Matrix Mini R4 × ${topic}`,
    totalSlides: 18,
    estimatedTime: "90 分鐘（2 節課）",
    slides,
  };
}
